# Generated by Django 2.1.1 on 2018-09-10 00:58

from django.db import migrations, models
import face_identify.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=200)),
                ('location', models.TextField(max_length=200)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=120)),
                ('Date', models.DateField(null=True)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=face_identify.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('print1', models.CharField(default='', max_length=120)),
                ('print2', models.CharField(default='', max_length=120)),
                ('print3', models.CharField(default='', max_length=120)),
                ('print4', models.CharField(default='', max_length=120)),
                ('print5', models.CharField(default='', max_length=120)),
                ('id_of_people', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
