# Generated by Django 2.1.1 on 2018-09-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_identify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_number', models.TextField(max_length=20000)),
                ('history', models.TextField(max_length=20000)),
            ],
        ),
        migrations.AlterField(
            model_name='list',
            name='location',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='list',
            name='question_text',
            field=models.TextField(max_length=20000),
        ),
    ]
