# Generated by Django 2.1.1 on 2018-09-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_identify', '0002_auto_20180910_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print1', models.CharField(default='', max_length=120)),
                ('print2', models.CharField(default='', max_length=120)),
                ('print3', models.CharField(default='', max_length=120)),
                ('print4', models.CharField(default='', max_length=120)),
                ('print5', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='history',
        ),
        migrations.AddField(
            model_name='history',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='Location',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
