# Generated by Django 2.1.1 on 2018-09-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_identify', '0003_auto_20180910_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='history_display1',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display10',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display2',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display3',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display4',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display5',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display6',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display7',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display8',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display9',
            field=models.CharField(default='', max_length=120),
        ),
    ]
