# Generated by Django 2.1.1 on 2018-09-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_identify', '0004_auto_20180910_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Location',
            field=models.CharField(choices=[('Hugo Boss', 'Hugo Boss'), ('Zara', 'Zara'), ('Boost', 'Boost'), ('StarBucks', 'StarBucks')], max_length=120),
        ),
    ]
