# Generated by Django 2.1.1 on 2018-09-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_identify', '0006_post_show_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='identified_person',
            field=models.CharField(default='', max_length=120),
        ),
    ]
