# Generated by Django 2.1.1 on 2018-09-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_identify', '0007_post_identified_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='history_display11',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display12',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display13',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display14',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display15',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display16',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display17',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display18',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display19',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display20',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display21',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display22',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display23',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display24',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display25',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display26',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display27',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display28',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display29',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='history_display30',
            field=models.CharField(default='', max_length=120),
        ),
    ]
